name: Generate Lookup Data

on:
  push:
    paths:
      - 'generate_*.py'
      - '.github/workflows/generate_data.yml'

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install mpmath numpy

      - name: Make data directory
        run: mkdir -p data

      - name: Generate zeros100k.npy
        run: python generate_zeros100k.py

      - name: Generate pi100k.npy
        run: python generate_pi100k.py

      - name: Commit lookup files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/zeros100k.npy data/pi100k.npy
          git commit -m "🔄 Generate lookup data"
          git push
