name: Generate Lookup Data

on:
  push:
    branches:
      - main

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install numpy

      - name: Download precomputed zeta zeros
        run: |
          mkdir -p data
          wget -q -O data/zeros_100k.txt https://www.dtc.umn.edu/~odlyzko/zeta_tables/zeta100k.txt
          python - << 'EOF'
import numpy as np
zeros = np.loadtxt("data/zeros_100k.txt")
np.save("data/zeros100k.npy", zeros)
EOF

      - name: Generate prime count lookup
        run: python generate_pi100k.py

      - name: Commit lookup files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/zeros100k.npy data/pi100k.npy
          git commit -m "🔄 Update lookup tables" || echo "No changes to commit"
          git push
