name: Generate Lookup Data

on:
  push:
    paths:
      - '.github/workflows/generate_data.yml'

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install numpy
      - name: Run generate scripts
        run: |
          python generate_zeros100k.py
          python generate_pi100k.py
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: data-files
          path: data/*.npy
